/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0hO4EmJVBf9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Home() {
  return (
    <div className="relative h-screen w-full">
      <img
        alt="Athlete"
        className="absolute inset-0 h-full w-full object-cover"
        src="/placeholder.svg"
      />
      <div className="absolute inset-0 bg-black/50" />
      <div className="relative z-10 flex h-full flex-col justify-between px-6 py-8">
        <div>
          <p className="mb-2 text-sm font-medium text-gray-300">
            Welcome! Today's workout is:
          </p>
          <h1 className="text-3xl font-bold text-white">Kettlebell Fire</h1>
        </div>
        <div>
          <div className="mb-4 rounded-lg bg-white/10 p-4 backdrop-blur-sm">
            <p className="mb-2 text-sm font-medium text-gray-300">
              Adapt if needed and start!
            </p>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div>
                <Label className="text-sm text-gray-300" htmlFor="room-size">
                  Room/Gym size
                </Label>
                <Select defaultValue="medium" id="room-size">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select size" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="yoga">Just a yoga mat</SelectItem>
                    <SelectItem value="rack">I have a rack</SelectItem>
                    <SelectItem value="park">I'm in a park</SelectItem>
                    <SelectItem value="garage">
                      I'm in my garage and can go out to run
                    </SelectItem>
                    <SelectItem value="gym">I'm in a crossfit gym</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label
                  className="text-sm text-gray-300"
                  htmlFor="time-available"
                >
                  How much time you have?
                </Label>
                <Select defaultValue="30" id="time-available">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select time" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="15">15 mins</SelectItem>
                    <SelectItem value="30">30 mins</SelectItem>
                    <SelectItem value="45">45 mins</SelectItem>
                    <SelectItem value="60">60 mins</SelectItem>
                    <SelectItem value="75">75 mins</SelectItem>
                    <SelectItem value="90">90 mins</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-sm text-gray-300" htmlFor="equipment">
                  What equipment you have?
                </Label>
                <Select defaultValue="kettlebell" id="equipment">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select equipment" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="kettlebell">Kettlebell</SelectItem>
                    <SelectItem value="dumbbells">Dumbbells</SelectItem>
                    <SelectItem value="barbell">Barbell and plates</SelectItem>
                    <SelectItem value="none">None</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
          <Link href="/workout" passHref legacyBehavior>
            <Button className="w-full">Start workout!</Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
